Gemfile
Gemfile.lock
app/controllers/api/v1/users_controller.rb
app/models/user.rb
db/migrate/20211124022637_create_users.rb
db/migrate/20211124165856_add_deleted_at_column_to_users.rb
db/migrate/20211124174046_add_role_id_column_to_users.rb
db/schema.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/models/user_spec.rb

Created the User model, controller, implemented soft delete and added roleId column (Waiting for the roles table to be created to work on the associations) and routes.
Extras: 
-Added pagination to users index with limit and offset
-Using representers to serialize user or users object, waiting for the team to select a serializer gem.

Feat ot112 17 create user model controller migration

---

app/controllers/roles_controller.rb
app/models/role.rb
db/migrate/20211124181428_create_roles.rb
db/schema.rb
spec/factories/roles.rb
spec/models/role_spec.rb
spec/requests/roles_spec.rb

First commit: Model and migration generated
Second commit: Controller generated
Also added specs generated for model and controller files.

Feat ot112 16 crear modelo migracion y controlador base de roles

---

.env.sample
app/controllers/api/v1/categories_controller.rb
app/controllers/categories_controller.rb
app/models/category.rb
app/models/user.rb
db/migrate/20211124232856_create_categories.rb
db/migrate/20211125194732_update_name_of_categories.rb
db/migrate/20211125195814_create_active_storage_tables.active_storage.rb
db/schema.rb
spec/factories/categories.rb
spec/factories/users.rb
spec/models/category_spec.rb
spec/models/user_spec.rb
spec/requests/categories_spec.rb

No puse el código del ticket que elegí en los 2 primeros commits

Feat ot112 18 crear modelo migración y controlador base de categories

---

app/controllers/api/v1/testimonials_controller.rb
app/models/testimonial.rb
db/migrate/20211125224937_create_testimonials.rb
db/schema.rb
spec/factories/testimonials.rb
spec/models/testimonial_spec.rb
spec/requests/api/v1/testimonials_spec.rb

This adds necessary changes required by:
https://alkemy-labs.atlassian.net/browse/OT112-20

Feat ot112 20 crear modelo migracion y controlador base de testimonials

---

README.md
app/controllers/api/v1/announcements_controller.rb
app/models/announcement.rb
db/migrate/20211125014024_create_announcements.rb
db/schema.rb
spec/factories/announcements.rb
spec/models/announcement_spec.rb
spec/requests/api/v1/announcements_spec.rb

This adds the necessary features to cover OT112-19.
https://alkemy-labs.atlassian.net/browse/OT112-19

Feat ot112 19 crear modelo migracion y controlador base de news

---

app/controllers/api/v1/users_controller.rb
app/controllers/application_controller.rb
app/controllers/authentication_controller.rb
app/services/auth_token_service.rb
lib/json_web_token.rb

- Add JWT logic to authenticate. 
- To complete feature:
-- <before_action :authorize_request, except: :create> 
<before_action :find_user, except: %i[create index]> **must be added to users controller**
--  <has_secure_password
validates :email, presence: true, uniqueness: true
validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
validates :username, presence: true, uniqueness: true
validates :password,
length: { minimum: 6 },
if: -> { new_record? || !password.nil? }> **must be added to User model**

Feat ot112 31 añadir logica de jwt

---

app/mailers/user_notifier_mailer.rb
app/views/user_notifier_mailer/send_email_to.html.erb
config/environment.rb
spec/mailers/previews/user_notifier_mailer_preview.rb
spec/mailers/user_notifier_mailer_spec.rb

Basic Email sender created, according to:
https://alkemy-labs.atlassian.net/browse/OT112-27

Feat ot112 27 integrar envio de emails

---

app/mailers/user_notifier_mailer.rb
app/models/user.rb
app/views/user_notifier_mailer/send_signup_email.html.erb

This adds features required by:
https://alkemy-labs.atlassian.net/browse/OT112-30

Feat ot112 30 envio de email de bienvenida

---

app/controllers/api/v1/users_controller.rb
config/routes.rb

- Add update method to users controller
- 
- Add path PATCH 'users/:id' to update users method

Ot112 34 endpoint de actualizar usuario

---

app/views/user_notifier_mailer/send_signup_email.html.erb

This modified the base template to comply with ticket requirements.
https://alkemy-labs.atlassian.net/browse/OT112-29

OT112-29: UserNotifierMailer Signup template added.

---

app/controllers/api/v1/users_controller.rb
app/controllers/application_controller.rb
app/serializers/user_serializer.rb

As requested in the ticket, when a user is created the AuthTokenService is called and a token is generated. It renders after the UserSerializer, and though it has some formatting errors (the user serializer renders in only one line) it works.

Feat ot112 50 return token after register

---

Gemfile
config/environments/development.rb
config/environments/production.rb
config/storage.yml

Changes applied to fit ticket requirements.
https://alkemy-labs.atlassian.net/browse/OT112-38

Feat ot112 38 setup amazon s3 sdk

---

app/models/announcement.rb
app/models/testimonial.rb

Typo fixes required to use `acts_as_paranoid` gem.

Fix ot112 19 20 announcements and testimonials typos

---

app/controllers/api/v1/auth_controller.rb
config/routes.rb

add path auth/me to routes
add get info at logged user to auth in auth controller

Feat ot112 36 endpoint datos usuario autenticado

---

app/models/activity.rb
db/migrate/20211201023330_create_activities.rb
spec/factories/activities.rb
spec/models/activity_spec.rb

Activity base model and migration created as ticket required:
https://alkemy-labs.atlassian.net/browse/OT112-48

Feat ot112 48 crear migracion y modelo de actividades

---

config/routes.rb

El método ya estaba creado, solo faltaba crear la ruta.

OT112-32: Destroy path added

---

app/controllers/api/v1/activities_controller.rb
app/controllers/api/v1/organizations_controller.rb
config/routes.rb

Added update method to activities controller, with set_activity as before action and error handling in case the provided params[:id] does not exist.

Feat ot112 52 update activities endpoint

---

app/controllers/api/v1/slides_controller.rb
app/serializers/slides_serializer.rb
config/routes.rb
db/schema.rb

Added slides controller with index action and a **slides** serializer that returns only the order and image, as the ticket requested, with admin verification also.

Feat ot112 56 slides index endpoint

---

app/controllers/api/v1/testimonials_controller.rb
app/models/testimonial.rb
app/serializers/testimonial_serializer.rb
config/routes.rb

Generé el serializer para este modelo, ojalá lo vieran  ya que tengo una duda con la foto que no está dentro del modelo.

Feat ot112 67 endpoint creacion testimonios

---

app/models/organization.rb
app/serializers/organization_serializer.rb
db/migrate/20211208200913_add_contact_urls_to_organizations.rb
db/schema.rb
spec/factories/organizations.rb
spec/models/organization_spec.rb

Migration and specs updated according to:
https://alkemy-labs.atlassian.net/browse/OT112-64

Feat ot112 64 agregar campos de contacto a organizations

---

Gemfile.lock
app/controllers/api/v1/contacts_controller.rb
app/serializers/contact_serializer.rb
config/routes.rb
spec/requests/contacts_spec.rb

**Ticket N° 55: Endpoint para almacenar contactos**
> Descripción
> COMO usuario
> QUIERO dar de alta contactos
> PARA que estén en la base de datos
> 
> Criterios de aceptación:
> 
> Se debe hacer una petición POST /contacts 
> -Se verificará que la petición contenga los campos name y email
Se agregó el controlador del modelo contact y su correspondiente serializer. También la ruta necesaria y el spec. 
En cuanto a la verificación de los campos name y email, se realizó dentro de la declaración del endpoint pero dentro de los params tuve que agregar phone y message, ya que en el modelo se validan esos campos y de otra manera no funcionaría.

Feat ot112 55 endpoint almacenar contactos

---

app/controllers/api/v1/users_controller.rb

Fix del controlador:
`status: ::unauthorized`
Veanlo para poder corregirlo.

Fixed line 12 of users controller

---

db/seeds.rb

Seeds added for both Roles and Users model. Required by:
https://alkemy-labs.atlassian.net/browse/OT112-75

OT112-75: Seed added for Roles and Users.

---

app/controllers/api/v1/members_controller.rb

Pagination added to Members model. Required by:
https://alkemy-labs.atlassian.net/browse/OT112-85
This should be merged AFTER #67, since I do not upload Gemfiles nor config files.

OT112-85: Pagination added to Members#index.

---

app/controllers/api/v1/announcements_controller.rb

- Fixed endpoints message format

fixed-announcements-endpoints-messages

---

app/controllers/api/v1/categories_controller.rb

- Fixed endpoints messages format

fixed-categories-endpoints-messages

---

app/controllers/api/v1/slides_controller.rb

- Fixed slides endpoints messages format

fixed-slides-endpoints-messages

---

app/controllers/api/v1/testimonials_controller.rb

- Fixed testimonials endpoints messages format

fixed-testimonials-endpoints-messages

---

app/controllers/api/v1/members_controller.rb

Fixed members endpoints messages format

fixed-members-endpoints-messages

---

app/controllers/api/v1/activities_controller.rb
app/controllers/api/v1/announcements_controller.rb
app/controllers/api/v1/categories_controller.rb
app/controllers/api/v1/members_controller.rb
app/controllers/api/v1/slides_controller.rb
app/controllers/api/v1/testimonials_controller.rb
app/controllers/api/v1/users_controller.rb
app/controllers/application_controller.rb

- Modified admin verify method in application_controller
- Admin Method added before_action in controllers where is necesary to portect admin endpoints

feat-OT112-76-change-admin-verify-method-and-added-before-action-in-controllers
